import type { RobotId, RobotState, GridPos } from "@tez/shared";
import type { WarehouseMap } from "@tez/core";
import type { Mission, AdapterEvent, RobotAdapter } from "./adapter.js";
import {
  MasterController,
  BlockingType,
  ConnectionState,
  createUuid,
  type AgvId,
  type ClientOptions,
  type VdaVersion,
  type Headerless,
  type Order as VdaOrder,
  type Node as VdaNode,
  type Edge as VdaEdge,
  type State as VdaState,
  type Error as VdaError,
} from "vda-5050-lib";

/**
 * Boundary-validation note (task-11 brief requirement: "ajv-validate orders
 * before send and states on receive"):
 *
 * No separate ajv setup or vendored VDA5050 JSON schema copies were added
 * here. `vda-5050-lib@1.7.2` already ships its own generated, per-version
 * validators compiled from the *official* VDA5050 JSON schemas — see
 * `node_modules/vda-5050-lib/common/vda-5050-validators-{1.1,2.0,2.1,3.0}.js`
 * (each file's header says "generated by a tool", i.e. schema-compiled
 * validation functions, not hand-written checks). `ClientOptions.topicObjectValidation`
 * (see `common/client.d.ts`) defaults to `{ inbound: true, outbound: true }`,
 * meaning EVERY order/instantActions object we publish and EVERY
 * state/connection object we receive is already validated against the
 * official schema for the selected `vdaVersion`, synchronously, before
 * publish (throws) / before dispatch to subscription handlers (invalid
 * inbound messages are dropped and reported, matching the brief's "invalid
 * inbound -> log + drop" requirement). We rely on this built-in validation
 * rather than duplicating it with a second, vendored ajv instance — that
 * would just be two schema copies that can drift out of sync. We do not
 * override `topicObjectValidation`, so both directions stay validated.
 */

export interface Vda5050AdapterOpts {
  /** VDA 5050 communication namespace. Defaults to "uagv". */
  interfaceName?: string;
  /** Protocol version. Only "2.0.0" is exercised by this codebase's tests. */
  vdaVersion?: VdaVersion;
}

/**
 * Per-robot bookkeeping for the VDA 5050 order currently mapped to that
 * robot's active `Mission`. Mirrors what `FakeAdapter` tracks internally
 * (`mission.id` + `nodeIds`), plus the VDA-specific `orderUpdateId` counter
 * and a `settled` flag used to dedupe terminal events across the multiple
 * `onOrderProcessed` handlers that a chain of order-update ("stitching")
 * calls installs for the same VDA orderId.
 */
interface TrackedOrder {
  orderId: string;
  orderUpdateId: number;
  /** Full logical path sent so far, for FakeAdapter-semantic prefix validation. */
  nodeIds: string[];
  /**
   * sequenceId assigned to the LAST node of the most recently sent VDA
   * order/order-update (i.e. `nodeIds[nodeIds.length - 1]`'s wire
   * sequenceId). A stitching order-update must repeat this exact
   * (nodeId, sequenceId) pair as its own first node — see
   * `agv-controller.js`'s `_isOrderBaseStitching` /
   * `_isOrderUpdateBaseStitching` (empirically verified: the library
   * rejects a stitching order with "stitching order base not extending
   * active order base" unless it starts by repeating the previous order's
   * last base node, continuing sequenceIds from there — resending the
   * FULL path from node 0 again, as the brief's phrasing might suggest, is
   * rejected).
   */
  lastSeq: number;
  settled: boolean;
}

const MAP_ID = "warehouse";

/**
 * RobotAdapter implementation over the real VDA 5050 protocol, built on
 * `vda-5050-lib`'s `MasterController` (coordination-plane control logic) per
 * the Task 3 spike. See that spike's header comment
 * (`packages/robot-interface/test/spike.test.ts`) for the exact API shape
 * this file relies on (constructor argument shapes, the 4-arg
 * `onOrderProcessed` callback, `ClientOptions.vdaVersion` being mandatory,
 * etc.) — the public `vda-5050-lib` docs/README examples on their own
 * describe a slightly different (older) surface.
 *
 * RobotId <-> VDA AgvId mapping: `RobotId` (a plain string, per
 * `@tez/shared`) is the AGV's `serialNumber`. The `manufacturer` is fixed
 * per robot at construction time via the `agvIds` list and is otherwise
 * opaque to the rest of the fleet-orchestration code.
 *
 * Mission -> VDA order mapping (see `RobotAdapter.sendMission` contract in
 * `adapter.ts`):
 * - `orderId = mission.id`.
 * - New mission id (or no order tracked yet for this robot) -> new VDA
 *   order, `orderUpdateId: 0`.
 * - Same mission id as the currently tracked order, with `mission.nodeIds`
 *   a strict-prefix-longer extension of the previously sent nodeIds (the
 *   exact `FakeAdapter` semantic) -> VDA "stitching order": same `orderId`,
 *   `orderUpdateId` incremented by 1. Per VDA 5050's own stitching-order
 *   rules (confirmed empirically against `agv-controller.js`, see the
 *   `TrackedOrder.lastSeq` doc comment below), the wire order for a
 *   stitching update does NOT resend the full path from node 0 — it repeats
 *   only the previous order's last base node (same nodeId + sequenceId, the
 *   "join point") followed by the newly appended nodes, with sequenceIds
 *   continuing on from there.
 * - Any other same-id nodeIds shape (shorter, or prefix mismatch) throws,
 *   matching the `@throws on invalid extension` contract.
 *
 * Node/edge sequenceIds follow the spike's confirmed even/odd numbering
 * (node i -> `2*i`, edge between node i and i+1 -> `2*i + 1`), offset by
 * `startSeq` (0 for a new order; the prior order's last sequenceId for a
 * stitching update) so sequenceIds keep increasing across updates instead
 * of restarting at 0 each time.
 */
export class Vda5050Adapter implements RobotAdapter {
  private readonly agvIdByRobotId = new Map<RobotId, AgvId>();
  private readonly clientOptions: ClientOptions;
  private mc: MasterController | undefined;
  private readonly handlers: Array<(e: AdapterEvent) => void> = [];

  private readonly orders = new Map<RobotId, TrackedOrder>();
  private readonly lastNodeIdByRobot = new Map<RobotId, string>();
  private readonly lastPosByRobot = new Map<RobotId, GridPos>();
  /**
   * Cached from the most recent `sendMission()` call, for snapping reported
   * `agvPosition` readings back onto the map grid in `handleState` — see
   * that method's doc comment for why this snap is necessary. There is only
   * ever one `WarehouseMap` in play per orchestrator run, so caching
   * whichever one was passed most recently is sufficient; `RobotAdapter`
   * does not thread a map into state-reporting paths.
   */
  private map: WarehouseMap | undefined;

  constructor(
    agvIds: Array<{ manufacturer: string; serialNumber: string }>,
    mqttUrl: string,
    opts?: Vda5050AdapterOpts
  ) {
    for (const id of agvIds) {
      this.agvIdByRobotId.set(id.serialNumber, {
        manufacturer: id.manufacturer,
        serialNumber: id.serialNumber,
      });
    }
    this.clientOptions = {
      interfaceName: opts?.interfaceName ?? "uagv",
      transport: { brokerUrl: mqttUrl },
      vdaVersion: opts?.vdaVersion ?? "2.0.0",
    };
  }

  async start(): Promise<void> {
    if (this.mc) return;
    const mc = new MasterController(this.clientOptions, {});
    await mc.start();

    // Single wildcard subscription covers every AGV in this interface
    // namespace rather than one subscription per robot.
    await mc.subscribe("state", {}, (state, subject) => {
      this.handleState(state, subject);
    });

    mc.trackAgvs((subject, connState) => {
      const robotId = subject.serialNumber;
      this.emit({
        type: "connection",
        robotId,
        online: connState === ConnectionState.Online,
      });
    });

    this.mc = mc;
  }

  async stop(): Promise<void> {
    if (!this.mc) return;
    const mc = this.mc;
    this.mc = undefined;
    await mc.stop();
  }

  async sendMission(m: Mission, map: WarehouseMap): Promise<void> {
    const mc = this.requireStarted();
    const agvId = this.requireAgvId(m.robotId);
    this.map = map;

    const prior = this.orders.get(m.robotId);
    const isExtension = !!prior && prior.orderId === m.id;

    let orderUpdateId: number;
    let pathNodeIds: string[]; // nodeIds actually included in THIS wire order, in order
    let startSeq: number;

    if (isExtension) {
      // prior is defined here (isExtension implies it); narrow for TS.
      const p = prior!;
      orderUpdateId = this.validateExtension(p, m.nodeIds);
      // A VDA 5050 stitching order must repeat the previous order's last
      // base node (same nodeId + sequenceId) as its own first node, then
      // continue with only the newly appended nodes — see the TrackedOrder
      // doc comment above for why resending the full path doesn't work.
      pathNodeIds = m.nodeIds.slice(p.nodeIds.length - 1);
      startSeq = p.lastSeq;
    } else {
      orderUpdateId = 0;
      pathNodeIds = m.nodeIds;
      startSeq = 0;
    }

    const nodes: VdaNode[] = pathNodeIds.map((nodeId, i) => {
      const pos = map.node(nodeId).pos;
      return {
        nodeId,
        sequenceId: startSeq + i * 2,
        released: true,
        nodePosition: { x: pos.x, y: pos.y, mapId: MAP_ID },
        actions: [],
      };
    });

    const edges: VdaEdge[] = [];
    for (let i = 0; i < pathNodeIds.length - 1; i++) {
      edges.push({
        edgeId: `${pathNodeIds[i]}-${pathNodeIds[i + 1]}`,
        sequenceId: startSeq + i * 2 + 1,
        released: true,
        startNodeId: pathNodeIds[i]!,
        endNodeId: pathNodeIds[i + 1]!,
        actions: [],
      });
    }

    const order: Headerless<VdaOrder> = {
      orderId: m.id,
      orderUpdateId,
      nodes,
      edges,
    };

    const lastSeq = startSeq + (pathNodeIds.length - 1) * 2;

    // Optimistically record the attempted state before publishing (reverted
    // on failure below) so that a follow-up sendMission() call issued before
    // this one's assignOrder() resolves computes its own prefix check
    // against what is actually in flight, not a stale snapshot.
    const previousEntry = prior;
    this.orders.set(m.robotId, {
      orderId: m.id,
      orderUpdateId,
      nodeIds: [...m.nodeIds],
      lastSeq,
      settled: false,
    });

    try {
      await mc.assignOrder(agvId, order, {
        onOrderProcessed: (withError, byCancelation, active) => {
          this.handleOrderProcessed(m.robotId, m.id, withError, byCancelation, active);
        },
      });
    } catch (err) {
      if (previousEntry) this.orders.set(m.robotId, previousEntry);
      else this.orders.delete(m.robotId);
      throw err;
    }
  }

  async cancelMission(robotId: RobotId): Promise<void> {
    const mc = this.requireStarted();
    const agvId = this.requireAgvId(robotId);

    await mc.initiateInstantActions(
      agvId,
      {
        // NB: despite the README example using `instantActions`, the actual
        // 1.7.2 runtime (controller/master-controller.js, initiateInstantActions)
        // reads `actions` for every vdaVersion except "1.1.0" and throws
        // (`Cannot read properties of undefined (reading 'forEach')`) if
        // that field is missing — verified empirically, not from the docs.
        actions: [
          {
            actionId: createUuid(),
            actionType: "cancelOrder",
            blockingType: BlockingType.Hard,
          },
        ],
      },
      {
        // The corresponding order's onOrderProcessed(byCancelation=true)
        // callback is what actually settles bookkeeping (see
        // handleOrderProcessed) — cancelMission() itself does not emit any
        // AdapterEvent, matching FakeAdapter's cancelMission contract.
        onActionStateChanged: () => {},
        onActionError: () => {},
      }
    );
  }

  on(handler: (e: AdapterEvent) => void): void {
    this.handlers.push(handler);
  }

  // ---- internals -----------------------------------------------------

  private requireStarted(): MasterController {
    if (!this.mc) throw new Error("Vda5050Adapter: start() must be called first");
    return this.mc;
  }

  private requireAgvId(robotId: RobotId): AgvId {
    const agvId = this.agvIdByRobotId.get(robotId);
    if (!agvId) {
      throw new Error(`Vda5050Adapter: unknown robot "${robotId}" (not in configured agvIds)`);
    }
    return agvId;
  }

  /**
   * Validates the FakeAdapter mission-extension semantic (strict-prefix,
   * strictly-longer) and returns the orderUpdateId to use for the resulting
   * VDA order update.
   */
  private validateExtension(prior: TrackedOrder, nodeIds: string[]): number {
    if (nodeIds.length <= prior.nodeIds.length) {
      throw new Error(
        `invalid mission extension: new nodeIds must be longer than current (got ${nodeIds.length}, need > ${prior.nodeIds.length})`
      );
    }
    for (let i = 0; i < prior.nodeIds.length; i++) {
      if (prior.nodeIds[i] !== nodeIds[i]) {
        throw new Error(
          `invalid mission extension: new nodeIds must preserve existing path. Mismatch at index ${i}: was "${prior.nodeIds[i]}", now "${nodeIds[i]}"`
        );
      }
    }
    return prior.orderUpdateId + 1;
  }

  /**
   * Handles a settlement callback from ONE `assignOrder()` call's event
   * handler. Because a stitched (order-update) leg installs a fresh handler
   * on every call while the VDA orderId stays the same, multiple handlers
   * may be alive for the same orderId at once; `entry.settled` ensures only
   * the first genuine terminal event for a given (robotId, missionId) pair
   * is ever emitted, and the `entry.orderId !== missionId` check discards
   * callbacks that fire after the robot has since moved on to a completely
   * different mission id (new leg or reassignment).
   */
  private handleOrderProcessed(
    robotId: RobotId,
    missionId: string,
    withError: VdaError | undefined,
    byCancelation: boolean,
    active: boolean
  ): void {
    const entry = this.orders.get(robotId);
    if (!entry || entry.orderId !== missionId || entry.settled) return;

    if (byCancelation) {
      // Matches FakeAdapter.cancelMission(): no AdapterEvent is emitted for
      // an intentional cancel: the orchestrator already deemed this
      // mission's fate settled by the time it called cancelMission.
      entry.settled = true;
      return;
    }
    if (withError) {
      entry.settled = true;
      this.emit({
        type: "missionFailed",
        robotId,
        missionId,
        reason: withError.errorDescription ?? withError.errorType,
      });
      return;
    }
    if (!active) {
      entry.settled = true;
      this.emit({ type: "missionDone", robotId, missionId });
    }
    // active === true, no error, not canceled: order processed but horizon
    // work remains. We never send horizon nodes (only released base nodes),
    // so this branch should not normally occur; if it does, there is
    // nothing to report yet.
  }

  private handleState(state: VdaState, subject: AgvId): void {
    const robotId: RobotId = subject.serialNumber;

    // missionProgress fires before the accompanying heartbeat "state" event
    // below, per the RobotAdapter per-tick event-ordering contract.
    if (state.lastNodeId && state.lastNodeId !== this.lastNodeIdByRobot.get(robotId)) {
      this.lastNodeIdByRobot.set(robotId, state.lastNodeId);
      if (state.orderId) {
        this.emit({
          type: "missionProgress",
          robotId,
          missionId: state.orderId,
          lastNodeId: state.lastNodeId,
        });
      }
    }

    const status: RobotState["status"] =
      state.errors.length > 0 ? "ERROR" : state.driving ? "EXECUTING" : "IDLE";

    // Snap the AGV's continuous agvPosition onto the nearest map node's
    // canonical (integer) coordinates rather than passing the raw float
    // x/y through. Orchestrator.resolveCurrentNodes() maps a robot's
    // reported pos back to a node via an EXACT cellKey match; a real AGV
    // mid-edge reports a continuously-interpolated position that essentially
    // never exactly equals a node's coordinates, which without this snap
    // makes the orchestrator quarantine the robot (position "unresolvable")
    // on almost every heartbeat — verified empirically against the fleet
    // integration test, which otherwise churns through
    // quarantine -> cancelMission -> requeue -> re-dispatch every couple of
    // ticks and never converges. Snapping is consistent with the rest of
    // the pipeline (dispatch/PIBT/reservations) already treating robot
    // position as node-discrete, not continuous.
    const pos: GridPos = state.agvPosition
      ? this.map
        ? this.map.node(this.map.nearestNode({ x: state.agvPosition.x, y: state.agvPosition.y })).pos
        : { x: state.agvPosition.x, y: state.agvPosition.y }
      : (this.lastPosByRobot.get(robotId) ?? { x: 0, y: 0 });
    this.lastPosByRobot.set(robotId, pos);

    const battery = Math.max(0, Math.min(1, state.batteryState.batteryCharge / 100));

    this.emit({
      type: "state",
      state: {
        id: robotId,
        pos,
        theta: state.agvPosition?.theta ?? 0,
        battery,
        status,
        currentMissionId: state.orderId ? state.orderId : undefined,
        lastSeen: state.timestamp || new Date().toISOString(),
      },
    });
  }

  private emit(event: AdapterEvent): void {
    for (const handler of this.handlers) {
      handler(event);
    }
  }
}
