import { DEFAULT_MAP_ID, type RobotId, type RobotState, type GridPos } from "@tez/shared";
import type { WarehouseMap } from "@tez/core";
import type { Mission, AdapterEvent, RobotAdapter } from "./adapter.js";
import {
  MasterController,
  BlockingType,
  ConnectionState,
  ErrorType,
  ErrorLevel,
  createUuid,
  type AgvId,
  type ClientOptions,
  type VdaVersion,
  type Headerless,
  type Order as VdaOrder,
  type Node as VdaNode,
  type Edge as VdaEdge,
  type State as VdaState,
  type Error as VdaError,
} from "vda-5050-lib";

/**
 * Boundary-validation note (task-11 brief requirement: "ajv-validate orders
 * before send and states on receive"):
 *
 * No separate ajv setup or vendored VDA5050 JSON schema copies were added
 * here. `vda-5050-lib@1.7.2` already ships its own generated, per-version
 * validators compiled from the *official* VDA5050 JSON schemas — see
 * `node_modules/vda-5050-lib/common/vda-5050-validators-{1.1,2.0,2.1,3.0}.js`
 * (each file's header says "generated by a tool", i.e. schema-compiled
 * validation functions, not hand-written checks). `ClientOptions.topicObjectValidation`
 * (see `common/client.d.ts`) defaults to `{ inbound: true, outbound: true }`,
 * meaning EVERY order/instantActions object we publish and EVERY
 * state/connection object we receive is already validated against the
 * official schema for the selected `vdaVersion`, synchronously, before
 * publish (throws) / before dispatch to subscription handlers (invalid
 * inbound messages are dropped and reported, matching the brief's "invalid
 * inbound -> log + drop" requirement). We rely on this built-in validation
 * rather than duplicating it with a second, vendored ajv instance — that
 * would just be two schema copies that can drift out of sync. We do not
 * override `topicObjectValidation`, so both directions stay validated.
 */

export interface Vda5050AdapterOpts {
  /** VDA 5050 communication namespace. Defaults to "uagv". */
  interfaceName?: string;
  /** Protocol version. Only "2.0.0" is exercised by this codebase's tests. */
  vdaVersion?: VdaVersion;
}

/**
 * Per-robot bookkeeping for the VDA 5050 order currently mapped to that
 * robot's active `Mission`. Mirrors what `FakeAdapter` tracks internally
 * (`mission.id` + `nodeIds`), plus the VDA-specific `orderUpdateId`
 * counter.
 *
 * C1 fix — mission id reuse deadlock: `missionId` (the `RobotAdapter`-level
 * `Mission.id`) is deliberately decoupled from `vdaOrderId` (the wire-level
 * VDA `orderId` actually used). Earlier this file used `missionId` directly
 * as the VDA `orderId`, which deadlocks the moment the SAME `missionId` is
 * reused after this robot's previous attempt at it was canceled or reached
 * a terminal outcome — which happens routinely, since `Orchestrator` mints
 * mission ids as `${orderId}:pick`/`${orderId}:drop` and reuses the exact
 * same id across retries of the same leg (e.g. a robot cancelled for going
 * offline, later revived and re-dispatched the same still-queued order). By
 * the time that reuse happens, the AGV/library already tore down the old
 * `orderId`'s lifecycle; replaying it (with `orderUpdateId: 0`, or as an
 * "extension" against stale tracked state) either gets silently rejected
 * with no forthcoming `onOrderProcessed`, or incorrectly validated as an
 * extension of an order that no longer exists on the AGV side — both are a
 * silent deadlock (the orchestrator waits forever for a `missionDone` that
 * will never come). See `Vda5050Adapter.sendMission`/`cancelMission`/
 * `handleOrderProcessed` for how a per-(robotId, missionId) attempt counter
 * mints a fresh `vdaOrderId` on every genuinely-new attempt.
 */
interface TrackedOrder {
  /** RobotAdapter-level Mission.id (orchestrator-facing). */
  missionId: string;
  /**
   * Wire-level VDA `orderId` in use for the CURRENT attempt at `missionId`.
   * Format: `${missionId}#${n}`, where `n` is a per-(robotId, missionId)
   * attempt counter that survives across cancel/terminal cycles (see
   * `nextAttemptVdaOrderId`) so a stale in-flight callback from an earlier
   * attempt can never be mistaken for the current one.
   */
  vdaOrderId: string;
  orderUpdateId: number;
  /** Full logical path sent so far, for FakeAdapter-semantic prefix validation. */
  nodeIds: string[];
  /**
   * sequenceId assigned to the LAST node of the most recently sent VDA
   * order/order-update (i.e. `nodeIds[nodeIds.length - 1]`'s wire
   * sequenceId). A stitching order-update must repeat this exact
   * (nodeId, sequenceId) pair as its own first node — see
   * `agv-controller.js`'s `_isOrderBaseStitching` /
   * `_isOrderUpdateBaseStitching` (empirically verified: the library
   * rejects a stitching order with "stitching order base not extending
   * active order base" unless it starts by repeating the previous order's
   * last base node, continuing sequenceIds from there — resending the
   * FULL path from node 0 again, as the brief's phrasing might suggest, is
   * rejected).
   */
  lastSeq: number;
}

/**
 * C2 fix — ERROR status latch: VDA5050 order/instant-action lifecycle
 * rejection notices (an order was invalid, superseded, or its stitching
 * didn't line up) are appended to the SAME `state.errors[]` array as
 * genuine AGV hardware/safety faults — see e.g. `agv-controller.js`'s
 * `_rejectOrder`/`_createOrderError`. These concern a dead ORDER, not robot
 * health, and per the library's own error-level semantics an AGV rejecting
 * one bad order is still "ready to start" (`errorLevel: "WARNING"`), never
 * `"FATAL"`. Excluded here (by known lifecycle errorType, defensively, and
 * separately by requiring `errorLevel: "FATAL"`) from the `RobotState.status
 * = "ERROR"` mapping in `handleState` below — otherwise a single rejected
 * order permanently latches the robot's reported status at ERROR even after
 * it's completely idle, healthy, and re-dispatchable.
 */
const ORDER_LIFECYCLE_ERROR_TYPES: ReadonlySet<string> = new Set<string>([
  ErrorType.Order,
  ErrorType.OrderUpdate,
  ErrorType.OrderNoRoute,
  ErrorType.OrderValidation,
  ErrorType.OrderAction,
  ErrorType.InstantAction,
  ErrorType.InstantActionValidation,
  ErrorType.InstantActionNoOrderToCancel,
]);

/**
 * RobotAdapter implementation over the real VDA 5050 protocol, built on
 * `vda-5050-lib`'s `MasterController` (coordination-plane control logic) per
 * the Task 3 spike. See that spike's header comment
 * (`packages/robot-interface/test/spike.test.ts`) for the exact API shape
 * this file relies on (constructor argument shapes, the 4-arg
 * `onOrderProcessed` callback, `ClientOptions.vdaVersion` being mandatory,
 * etc.) — the public `vda-5050-lib` docs/README examples on their own
 * describe a slightly different (older) surface.
 *
 * RobotId <-> VDA AgvId mapping: `RobotId` (a plain string, per
 * `@tez/shared`) is the AGV's `serialNumber`. The `manufacturer` is fixed
 * per robot at construction time via the `agvIds` list and is otherwise
 * opaque to the rest of the fleet-orchestration code. CAVEAT (I2): since
 * `RobotId` carries no manufacturer component, a multi-manufacturer fleet
 * where two different manufacturers happen to reuse the same serialNumber
 * will collide under this scheme (the second one silently maps onto the
 * first one's RobotId). Configure distinct serialNumbers across
 * manufacturers, or extend the RobotId mapping, if that's a real risk for a
 * given deployment — not addressed here.
 *
 * Mission -> VDA order mapping (see `RobotAdapter.sendMission` contract in
 * `adapter.ts`). NOTE (C1): the wire-level VDA `orderId` is NOT simply
 * `mission.id` — see the `TrackedOrder` doc comment above for why that
 * deadlocks on mission id reuse, and `nextAttemptVdaOrderId` for the actual
 * `${missionId}#${n}` scheme:
 * - New mission id (or no LIVE order tracked for this robot under that
 *   mission id — i.e. the robot's previous attempt at it, if any, was
 *   already canceled or reached a terminal outcome) -> fresh VDA order,
 *   `orderUpdateId: 0`, on a freshly-minted `vdaOrderId`.
 * - Same mission id as the CURRENTLY LIVE tracked order, with
 *   `mission.nodeIds` a strict-prefix-longer extension of the previously
 *   sent nodeIds (the exact `FakeAdapter` semantic) -> VDA "stitching
 *   order" on the SAME `vdaOrderId`, `orderUpdateId` incremented by 1. Per
 *   VDA 5050's own stitching-order rules (confirmed empirically against
 *   `agv-controller.js`, see the `TrackedOrder.lastSeq` doc comment above),
 *   the wire order for a stitching update does NOT resend the full path
 *   from node 0 — it repeats only the previous order's last base node
 *   (same nodeId + sequenceId, the "join point") followed by the newly
 *   appended nodes, with sequenceIds continuing on from there.
 * - Any other same-missionId nodeIds shape against a currently live order
 *   (shorter, or prefix mismatch) throws, matching the `@throws on invalid
 *   extension` contract.
 *
 * Node/edge sequenceIds follow the spike's confirmed even/odd numbering
 * (node i -> `2*i`, edge between node i and i+1 -> `2*i + 1`), offset by
 * `startSeq` (0 for a new order; the prior order's last sequenceId for a
 * stitching update) so sequenceIds keep increasing across updates instead
 * of restarting at 0 each time.
 */
export class Vda5050Adapter implements RobotAdapter {
  private readonly agvIdByRobotId = new Map<RobotId, AgvId>();
  private readonly clientOptions: ClientOptions;
  private mc: MasterController | undefined;
  private readonly handlers: Array<(e: AdapterEvent) => void> = [];

  private readonly orders = new Map<RobotId, TrackedOrder>();
  /**
   * C1: per-(robotId, missionId) attempt counter, keyed `${robotId}::${missionId}`.
   * Deliberately NEVER cleared (unlike `orders`, which only tracks the
   * currently-live attempt) — it must keep incrementing across
   * cancel/terminal cycles so a third attempt at the same missionId gets
   * `#2`, not a repeat of `#0`.
   *
   * Operational growth note (documented rather than pruned, by design):
   * this map holds exactly one entry per DISTINCT `(robotId, missionId)`
   * pair the adapter has ever seen, for the lifetime of the process. Since
   * `Orchestrator` mints mission ids as `${orderId}:pick`/`${orderId}:drop`
   * and `orderId`s are minted fresh per transport order, growth is
   * proportional to total orders processed (roughly 2 entries/order) —
   * unbounded over a long-running process, but each entry is a tiny
   * `string -> number` pair, so this is a slow, low-memory-per-entry
   * growth, not a leak in the "holds onto large objects" sense.
   * Pruning on `orders`-entry-clear was deliberately NOT implemented: an
   * entry can only safely be dropped once we're certain the corresponding
   * `vdaOrderId` (and, transitively, any retained-message or cached
   * library-side state referencing it) will never be revisited, which
   * isn't something this adapter can determine on its own without
   * re-introducing the exact ambiguity C1 fixes. If this ever needs
   * bounding in practice (e.g. a process that runs for a very long time
   * across a very large number of orders), an LRU or periodic sweep keyed
   * on `orders`-entry-clear time would be the place to add it.
   *
   * #8: `stop()` IS an exception to "never cleared" — a full adapter
   * shutdown is exactly the point at which "never revisited again" becomes
   * true for every tracked attempt, so `stop()` clears this map too (along
   * with the other per-robot tracking maps below) rather than leaking it
   * for the remaining process lifetime.
   */
  private readonly attemptCounters = new Map<string, number>();
  private readonly lastNodeIdByRobot = new Map<RobotId, string>();
  private readonly lastPosByRobot = new Map<RobotId, GridPos>();
  /** I2: serials we've already logged an "unconfigured AGV" warning for, so we log once, not once per heartbeat. */
  private readonly warnedUnknownRobots = new Set<string>();
  /**
   * Cached from the most recent `sendMission()` call, for snapping reported
   * `agvPosition` readings back onto the map grid in `handleState` — see
   * that method's doc comment for why this snap is necessary. There is only
   * ever one `WarehouseMap` in play per orchestrator run, so caching
   * whichever one was passed most recently is sufficient; `RobotAdapter`
   * does not thread a map into state-reporting paths.
   */
  private map: WarehouseMap | undefined;

  constructor(
    agvIds: Array<{ manufacturer: string; serialNumber: string }>,
    mqttUrl: string,
    opts?: Vda5050AdapterOpts
  ) {
    for (const id of agvIds) {
      this.agvIdByRobotId.set(id.serialNumber, {
        manufacturer: id.manufacturer,
        serialNumber: id.serialNumber,
      });
    }
    this.clientOptions = {
      interfaceName: opts?.interfaceName ?? "uagv",
      transport: { brokerUrl: mqttUrl },
      vdaVersion: opts?.vdaVersion ?? "2.0.0",
    };
  }

  async start(): Promise<void> {
    if (this.mc) return;
    const mc = new MasterController(this.clientOptions, {});
    await mc.start();

    // Single wildcard subscription covers every AGV in this interface
    // namespace rather than one subscription per robot. I2: this also
    // means ANY AGV sharing this broker+interfaceName is heard, including
    // ones outside our configured fleet — filtered out below.
    await mc.subscribe("state", {}, (state, subject) => {
      this.handleState(state, subject);
    });

    mc.trackAgvs((subject, connState) => {
      const robotId = subject.serialNumber;
      if (!this.isConfiguredRobot(robotId)) return; // I2
      this.emit({
        type: "connection",
        robotId,
        online: connState === ConnectionState.Online,
      });
    });

    this.mc = mc;
  }

  async stop(): Promise<void> {
    if (!this.mc) return;
    const mc = this.mc;
    this.mc = undefined;
    await mc.stop();

    // #8: release every per-robot tracking map so a stopped adapter doesn't
    // pin memory for a fleet it's no longer serving. Safe ONLY here — this
    // is the adapter's full shutdown, not a mid-operation event — never
    // clear these during normal running (see e.g. `attemptCounters`' own
    // doc comment on why it must otherwise survive cancel/terminal cycles
    // within a live run). A subsequent start() begins a fresh tracking
    // session from empty maps, matching a real AGV fleet reconnecting from
    // scratch.
    this.orders.clear();
    this.attemptCounters.clear();
    this.lastNodeIdByRobot.clear();
    this.lastPosByRobot.clear();
    this.warnedUnknownRobots.clear();
  }

  async sendMission(m: Mission, map: WarehouseMap): Promise<void> {
    const mc = this.requireStarted();
    const agvId = this.requireAgvId(m.robotId);
    this.map = map;

    const prior = this.orders.get(m.robotId);
    // C1: "extension" means the CURRENTLY LIVE tracked order is for this
    // exact missionId. Because cancelMission() and handleOrderProcessed()
    // both delete the tracked entry the moment an attempt is canceled or
    // reaches a terminal outcome (see those methods), `prior` existing at
    // all with a matching missionId already implies it's the same live
    // attempt, not a stale one — no separate "settled" flag needed.
    const isExtension = !!prior && prior.missionId === m.id;

    let vdaOrderId: string;
    let orderUpdateId: number;
    let pathNodeIds: string[]; // nodeIds actually included in THIS wire order, in order
    let startSeq: number;

    if (isExtension) {
      // prior is defined here (isExtension implies it); narrow for TS.
      const p = prior!;
      orderUpdateId = this.validateExtension(p, m.nodeIds);
      vdaOrderId = p.vdaOrderId;
      // A VDA 5050 stitching order must repeat the previous order's last
      // base node (same nodeId + sequenceId) as its own first node, then
      // continue with only the newly appended nodes — see the TrackedOrder
      // doc comment above for why resending the full path doesn't work.
      pathNodeIds = m.nodeIds.slice(p.nodeIds.length - 1);
      startSeq = p.lastSeq;
    } else {
      // C1: fresh VDA order under a freshly-minted vdaOrderId — see the
      // TrackedOrder / class doc comments for why we can't just reuse
      // missionId (or the previous vdaOrderId) here.
      orderUpdateId = 0;
      vdaOrderId = this.nextAttemptVdaOrderId(m.robotId, m.id);
      pathNodeIds = m.nodeIds;
      startSeq = 0;
    }

    const nodes: VdaNode[] = pathNodeIds.map((nodeId, i) => {
      const pos = map.node(nodeId).pos;
      return {
        nodeId,
        sequenceId: startSeq + i * 2,
        released: true,
        nodePosition: { x: pos.x, y: pos.y, mapId: DEFAULT_MAP_ID },
        actions: [],
      };
    });

    const edges: VdaEdge[] = [];
    for (let i = 0; i < pathNodeIds.length - 1; i++) {
      edges.push({
        edgeId: `${pathNodeIds[i]}-${pathNodeIds[i + 1]}`,
        sequenceId: startSeq + i * 2 + 1,
        released: true,
        startNodeId: pathNodeIds[i]!,
        endNodeId: pathNodeIds[i + 1]!,
        actions: [],
      });
    }

    const order: Headerless<VdaOrder> = {
      orderId: vdaOrderId,
      orderUpdateId,
      nodes,
      edges,
    };

    const lastSeq = startSeq + (pathNodeIds.length - 1) * 2;

    // Optimistically record the attempted state before publishing (reverted
    // on failure below) so that a follow-up sendMission() call issued before
    // this one's assignOrder() resolves computes its own prefix check
    // against what is actually in flight, not a stale snapshot.
    const previousEntry = prior;
    this.orders.set(m.robotId, {
      missionId: m.id,
      vdaOrderId,
      orderUpdateId,
      nodeIds: [...m.nodeIds],
      lastSeq,
    });

    try {
      await mc.assignOrder(agvId, order, {
        onOrderProcessed: (withError, byCancelation, active) => {
          this.handleOrderProcessed(m.robotId, m.id, vdaOrderId, withError, byCancelation, active);
        },
      });
    } catch (err) {
      if (previousEntry) this.orders.set(m.robotId, previousEntry);
      else this.orders.delete(m.robotId);
      throw err;
    }
  }

  async cancelMission(robotId: RobotId): Promise<void> {
    const mc = this.requireStarted();
    const agvId = this.requireAgvId(robotId);

    // C1: clear tracked bookkeeping immediately, synchronously — not only
    // on the eventual async onOrderProcessed(byCancelation=true)
    // confirmation — so a same-missionId re-send issued right after this
    // call (e.g. the orchestrator's offline-timeout/quarantine paths
    // cancel then requeue, sometimes within the same tick) is correctly
    // treated as a fresh VDA order rather than an "extension" of an order
    // that's already being torn down. See the TrackedOrder/class doc
    // comments for the deadlock this prevents.
    this.orders.delete(robotId);

    await mc.initiateInstantActions(
      agvId,
      {
        // NB: despite the README example using `instantActions`, the actual
        // 1.7.2 runtime (controller/master-controller.js, initiateInstantActions)
        // reads `actions` for every vdaVersion except "1.1.0" and throws
        // (`Cannot read properties of undefined (reading 'forEach')`) if
        // that field is missing — verified empirically, not from the docs.
        actions: [
          {
            actionId: createUuid(),
            actionType: "cancelOrder",
            blockingType: BlockingType.Hard,
          },
        ],
      },
      {
        // The corresponding order's onOrderProcessed(byCancelation=true)
        // callback is what actually settles bookkeeping (see
        // handleOrderProcessed) — cancelMission() itself does not emit any
        // AdapterEvent, matching FakeAdapter's cancelMission contract.
        onActionStateChanged: () => {},
        onActionError: () => {},
      }
    );
  }

  on(handler: (e: AdapterEvent) => void): void {
    this.handlers.push(handler);
  }

  /** Test-only hook: live entry counts for every per-robot tracking map, for asserting #8's stop() cleanup empties them all. */
  _trackingSizes(): Record<string, number> {
    return {
      orders: this.orders.size,
      attemptCounters: this.attemptCounters.size,
      lastNodeIdByRobot: this.lastNodeIdByRobot.size,
      lastPosByRobot: this.lastPosByRobot.size,
      warnedUnknownRobots: this.warnedUnknownRobots.size,
    };
  }

  // ---- internals -----------------------------------------------------

  private requireStarted(): MasterController {
    if (!this.mc) throw new Error("Vda5050Adapter: start() must be called first");
    return this.mc;
  }

  private requireAgvId(robotId: RobotId): AgvId {
    const agvId = this.agvIdByRobotId.get(robotId);
    if (!agvId) {
      throw new Error(`Vda5050Adapter: unknown robot "${robotId}" (not in configured agvIds)`);
    }
    return agvId;
  }

  /**
   * I2: true if `robotId` (an AGV serialNumber) is part of this adapter's
   * configured fleet. Both the wildcard "state" subscription and
   * `trackAgvs()` in `start()` hear every AGV sharing this broker +
   * interfaceName, not just ours — logs the first sighting of an unknown
   * serial once (not per heartbeat) rather than silently ignoring it
   * forever, so a misconfiguration is still discoverable.
   */
  private isConfiguredRobot(robotId: RobotId): boolean {
    if (this.agvIdByRobotId.has(robotId)) return true;
    if (!this.warnedUnknownRobots.has(robotId)) {
      this.warnedUnknownRobots.add(robotId);
      // eslint-disable-next-line no-console
      console.warn(
        `Vda5050Adapter: ignoring state/connection from unconfigured AGV serialNumber "${robotId}" ` +
          `— not in configured agvIds. (RobotId = serialNumber only; a multi-manufacturer fleet ` +
          `reusing this serialNumber under a different manufacturer would otherwise collide.)`
      );
    }
    return false;
  }

  /**
   * C1: mints the next per-(robotId, missionId) wire orderId, formatted
   * `${missionId}#${n}`. `n` is tracked in `attemptCounters` (keyed
   * `${robotId}::${missionId}`), which is never cleared — see that field's
   * doc comment for why it must keep incrementing across cancel/terminal
   * cycles.
   */
  private nextAttemptVdaOrderId(robotId: RobotId, missionId: string): string {
    const key = `${robotId}::${missionId}`;
    const n = (this.attemptCounters.get(key) ?? -1) + 1;
    this.attemptCounters.set(key, n);
    return `${missionId}#${n}`;
  }

  /**
   * Reverse-maps a wire-level VDA `orderId` (as echoed back in a `State`
   * message's `orderId` field) to the RobotAdapter-level `Mission.id` the
   * orchestrator actually sent — needed because C1 decoupled the two.
   * Returns `undefined` when there's no currently-live tracked order
   * matching that exact `vdaOrderId` for this robot (e.g. the mission
   * already completed/failed/was canceled and its tracked entry was
   * cleared, matching `FakeAdapter`'s own `currentMissionId = undefined`
   * behavior once a mission ends).
   */
  private resolveMissionId(robotId: RobotId, vdaOrderId: string): string | undefined {
    if (!vdaOrderId) return undefined;
    const entry = this.orders.get(robotId);
    return entry && entry.vdaOrderId === vdaOrderId ? entry.missionId : undefined;
  }

  /**
   * Validates the FakeAdapter mission-extension semantic (strict-prefix,
   * strictly-longer) and returns the orderUpdateId to use for the resulting
   * VDA order update.
   */
  private validateExtension(prior: TrackedOrder, nodeIds: string[]): number {
    if (nodeIds.length <= prior.nodeIds.length) {
      throw new Error(
        `invalid mission extension: new nodeIds must be longer than current (got ${nodeIds.length}, need > ${prior.nodeIds.length})`
      );
    }
    for (let i = 0; i < prior.nodeIds.length; i++) {
      if (prior.nodeIds[i] !== nodeIds[i]) {
        throw new Error(
          `invalid mission extension: new nodeIds must preserve existing path. Mismatch at index ${i}: was "${prior.nodeIds[i]}", now "${nodeIds[i]}"`
        );
      }
    }
    return prior.orderUpdateId + 1;
  }

  /**
   * Handles a settlement callback from ONE `assignOrder()` call's event
   * handler. Because a stitched (order-update) leg installs a fresh handler
   * on every call while the vdaOrderId stays the same, multiple handlers
   * may be alive for the same vdaOrderId at once; deleting `orders`'s entry
   * on the FIRST terminal callback ensures only one terminal AdapterEvent is
   * ever emitted per attempt, and the `entry.vdaOrderId !== vdaOrderId`
   * check (C1: keyed on the SPECIFIC attempt, not just missionId) discards
   * callbacks that fire after the robot has since moved on — to a
   * completely different mission id, OR to a fresh retry attempt of the
   * SAME mission id under a new vdaOrderId.
   */
  private handleOrderProcessed(
    robotId: RobotId,
    missionId: string,
    vdaOrderId: string,
    withError: VdaError | undefined,
    byCancelation: boolean,
    active: boolean
  ): void {
    const entry = this.orders.get(robotId);
    if (!entry || entry.vdaOrderId !== vdaOrderId) return;

    if (byCancelation) {
      // C1: cancelMission() already cleared bookkeeping synchronously when
      // it initiated the cancel; this is just the async confirmation
      // arriving. No AdapterEvent, matching FakeAdapter.cancelMission's
      // contract (best-effort, silent). Deleting again here is a no-op in
      // the common case and a safety net if this ever fires without our
      // own cancelMission having run first.
      this.orders.delete(robotId);
      return;
    }
    if (withError) {
      this.orders.delete(robotId);
      this.emit({
        type: "missionFailed",
        robotId,
        missionId,
        reason: withError.errorDescription ?? withError.errorType,
      });
      return;
    }
    if (!active) {
      this.orders.delete(robotId);
      this.emit({ type: "missionDone", robotId, missionId });
    }
    // active === true, no error, not canceled: order processed but horizon
    // work remains. We never send horizon nodes (only released base nodes),
    // so this branch should not normally occur; if it does, there is
    // nothing to report yet — and nothing to clear, so the entry is left
    // live for the next stitching update.
  }

  private handleState(state: VdaState, subject: AgvId): void {
    const robotId: RobotId = subject.serialNumber;
    if (!this.isConfiguredRobot(robotId)) return; // I2

    // missionProgress fires before the accompanying heartbeat "state" event
    // below, per the RobotAdapter per-tick event-ordering contract. C1:
    // state.orderId is the wire-level vdaOrderId, not the RobotAdapter
    // missionId — reverse-mapped via resolveMissionId (undefined when it
    // doesn't match anything we currently have tracked, e.g. a stale echo
    // of an already-completed order).
    if (state.lastNodeId && state.lastNodeId !== this.lastNodeIdByRobot.get(robotId)) {
      this.lastNodeIdByRobot.set(robotId, state.lastNodeId);
      const missionId = this.resolveMissionId(robotId, state.orderId);
      if (missionId) {
        this.emit({
          type: "missionProgress",
          robotId,
          missionId,
          lastNodeId: state.lastNodeId,
        });
      }
    }

    // C2: only a FATAL-level error whose type isn't a known order/instant-
    // action lifecycle rejection latches ERROR status — see
    // ORDER_LIFECYCLE_ERROR_TYPES's doc comment above.
    const hasFatalHardwareError = state.errors.some(
      (e) => e.errorLevel === ErrorLevel.Fatal && !ORDER_LIFECYCLE_ERROR_TYPES.has(e.errorType)
    );
    const status: RobotState["status"] = hasFatalHardwareError ? "ERROR" : state.driving ? "EXECUTING" : "IDLE";

    // Snap the AGV's continuous agvPosition onto the nearest map node's
    // canonical (integer) coordinates rather than passing the raw float
    // x/y through. Orchestrator.resolveCurrentNodes() maps a robot's
    // reported pos back to a node via an EXACT cellKey match; a real AGV
    // mid-edge reports a continuously-interpolated position that essentially
    // never exactly equals a node's coordinates, which without this snap
    // makes the orchestrator quarantine the robot (position "unresolvable")
    // on almost every heartbeat — verified empirically against the fleet
    // integration test, which otherwise churns through
    // quarantine -> cancelMission -> requeue -> re-dispatch every couple of
    // ticks and never converges. Snapping is consistent with the rest of
    // the pipeline (dispatch/PIBT/reservations) already treating robot
    // position as node-discrete, not continuous.
    const pos: GridPos = state.agvPosition
      ? this.map
        ? this.map.node(this.map.nearestNode({ x: state.agvPosition.x, y: state.agvPosition.y })).pos
        : { x: state.agvPosition.x, y: state.agvPosition.y }
      : (this.lastPosByRobot.get(robotId) ?? { x: 0, y: 0 });
    this.lastPosByRobot.set(robotId, pos);

    const battery = Math.max(0, Math.min(1, state.batteryState.batteryCharge / 100));

    this.emit({
      type: "state",
      state: {
        id: robotId,
        pos,
        theta: state.agvPosition?.theta ?? 0,
        battery,
        status,
        currentMissionId: this.resolveMissionId(robotId, state.orderId),
        lastSeen: state.timestamp || new Date().toISOString(),
      },
    });
  }

  private emit(event: AdapterEvent): void {
    for (const handler of this.handlers) {
      handler(event);
    }
  }
}
